### ISSUE TITLE
Ascent Manager EPIC rewrite

### ISSUE THREAD

**Issue by lamont-granquist** [MuMech/MechJeb2#1053]
The Shuttle PEG rewrite is here:

- https://github.com/lamont-granquist/MechJeb2/releases

That had issues which make it not generally viable for public consumption.

A new version of that guidance is being rewritten which will do more exact trajectory calculations without the clipping issues of PEG, that will solve a lot of problem.  The feature set it will ultimately target includes:

- [ ] timed launches to only LAN of target / user-entered LAN
- [ ] launches to selected keplerian coordinates, with the unselected ones being optimized.
- [ ] launch to rendezvous that works without a prelaunch
- [ ] suborbital launches to a desired altitude (and keplerian targets like inc) with the final velocity being maximized after the stage burns out
- [ ] direct ascent to a moon
- [ ] optimized coasts
- [ ] direct ascent to interplanetary (wishlist)
- [ ] node executor rewrite using that guidance under the covers
- [ ] landing guidance rewrite using that guidance under the covers (#1052)

**Comment by lamont-granquist** [comment]
gah, i can't believe i opened two identical epic issues, need more coffee, #1061 mostly has more detail now.
