### ISSUE TITLE
Advanced Planetary Transfer EPIC rollup / rewrite

### ISSUE THREAD

**Issue by lamont-granquist** [MuMech/MechJeb2#1060]
- [ ] Be competitive with KSP TOT
- [ ] Free returns
- [ ] Gravity Assists
- [ ] Gravity Assists around a Moon
- [ ] target periapsis and inclination around target
- [ ] Principia-all-the-things
